export const pageContainer = {
    backgroundColor: "#dfdfdf",
    padding: "3rem",
    paddingBottom: "3rem",
    width: "50rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    boxSizing: "border-box",
    flex: "1 0 auto",
    boxShadow: "inset 5px 5px 10px rgba(0, 0, 0, 0.3), inset -5px -5px 10px rgba(0, 0, 0, 0.3)",
  };
export const innerPageContainer = {
    padding: "2rem",
    backgroundColor: "#ffffff",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.15), 0 4px 10px rgba(0, 0, 0, 0.1)",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    border: "solid 1px black",
    boxSizing: "border-box",
    flex: "1 0 auto",
};